### ISSUE TITLE
how do I use this script?

### ISSUE THREAD

**Issue by Pancho111** [atask/interstice#1]
Hi ,
how do I use this script?
I have a mac computer and I would like to record for example this station from shoutcast .
http://server-26.stream-server.nl:8706/stream
your response will be appreciated .
thank you

**Comment by atask** [comment]
Hello,
this is the API repository, in case you want to use Interstice from another project. If you just want to use it from command line, [interstice-cli](https://github.com/atask/interstice-cli) is what you are looking for.
